---
title: "Week 4 Notes"
author: "pdwessel"
date: "September 28, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Editing Text Variables

#Fixing character vectors - tolower(), toupper()
```{r}
fileUrl <- "https://data.baltimorecity.gov/api/views/dz54-2aru/rows.csv?accessType=DOWNLOAD"
if(!file.exists("./data/cameras.csv")) {
  download.file(fileUrl, destfile="./data/cameras.csv", method="curl")
}
cameraData <- read.csv("./data/cameras.csv")
names(cameraData)

tolower(names(cameraData))
```

```{r}
splitNames <- strsplit(names(cameraData), "\\.")
splitNames[[5]]
splitNames[[6]]
```

```{r}
mylist <- list(letters = c("A", "b", "c"), numbers = 1:3, matrix(1:25, ncol = 5))
head(mylist)
```

```{r}
firstElement <- function(x){x[1]}
sapply(splitNames,firstElement)
```

```{r}
fileUrl1 = "https://dl.dropboxusercontent.com/u/7710864/data/reviews-apr29.csv"
fileUrl2 = "https://dl.dropboxusercontent.com/u/7710864/data/solutions-apr29.csv"
if (!file.exists("./data/reviews.csv")) {
    download.file(fileUrl1, destfile = "./data/reviews.csv", method = "curl")
}
if (!file.exists("./data/solutions.csv")) {
    download.file(fileUrl2, destfile = "./data/solutions.csv", method = "curl")
}
reviews = read.csv("./data/reviews.csv")
solutions = read.csv("./data/solutions.csv")
head(reviews, 2)
```


```{r}

sub("_","",names(reviews))

```

#Finding Values - grep(), grepl()
```{r}
grep("Alameda", cameraData$intersection)

table(grepl("Alameda", cameraData$intersection))

cameraData2 <- cameraData[!grepl("Alameda", cameraData$intersection),]
```

#Creating Dates
```{r}
x=c("1jan1960", "2jan1960", "30jul1954")
z = as.Date(x, "%d%b%Y")
z
```







```
