---
title: "Week 1 Notes"
author: "pdwessel"
date: "November 15, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Lesson 1: Graphs
###Principles of Analytic Graphics

(@) Principle 1: Show Comparison
* Evidence for a hypothesis is always *relative* to another competing hypothesis.
* Always ask "Compared to what?"

(@) Principle 2: Show causality, mechanism, explination, systematic structure
* What is your causal framework for thinking about a question?

(@) Principle 3: Show multivariate data
* Multivariate = more than 2 variables
* The real world in multivariate
* Need to "escape flatland"

(@) Principle 4: Integration of evidence
* Completely integrate words, numbers, images, diagrams
* Data graphics should make use of many modes of data presentation
* Don't let the tool drive the analysis

(@) Principle 5: Describe and document the evidence with appropiate labels, scales, sources, etc.
* A data graphic should tell a complete story that is credible

(@) Principle 6: Content is king
* Analytical presentations ultimately stand or fall depending on the quality, relevance, and integrity of their content

### Exploratory Graphs

Resources :
* R Graph Library
* r Blogger

##Lesson 2: Plotting

###Plotting Systems in R

The base plotting system

* "Artist's palette" model
* Start with a blank canvas and build up from there
* Start with plot function (or similiar)
* Use annotation functions to add/modify (text, lines, labels)

The lattice system

* In the lattice package
* plots are created with a single function call (xyplot, bwplot, etc.)
* most useful for conditioning types of plots. Looking at how y changes with x across levels of z
* Things like margins/spacing set automatically
* Somewhat akward to speficy am entire plot in a single function call

The ggplot2 system

* Splits the differnce between base and lattice in a number of ways
* superficial similiarity to lattice but generally more easier to learn/customize

###Base Plotting systems

Key factors in the base plotting system:

* A 
